// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: common.proto

package meproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Opcode int32

const (
	// /////////////////////////////////////////////////////////////////////////////////////////////////
	// Common OpcodeID
	Opcode_ID_Null          Opcode = 0
	Opcode_ID_CommonMessage Opcode = 1
	Opcode_ID_ErrorMessage  Opcode = 2 ///////////////////////////////////////////////////////////////////////////////////////////////////
)

// Enum value maps for Opcode.
var (
	Opcode_name = map[int32]string{
		0: "ID_Null",
		1: "ID_CommonMessage",
		2: "ID_ErrorMessage",
	}
	Opcode_value = map[string]int32{
		"ID_Null":          0,
		"ID_CommonMessage": 1,
		"ID_ErrorMessage":  2,
	}
)

func (x Opcode) Enum() *Opcode {
	p := new(Opcode)
	*p = x
	return p
}

func (x Opcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Opcode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Opcode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Opcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Opcode.Descriptor instead.
func (Opcode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	// /////////////////////////////////////////////////////////////////////////////////////////////////
	// Common Error
	ErrorCode_Error_OK        ErrorCode = 0 //None Error, Success!
	ErrorCode_Error_Parameter ErrorCode = 1
	ErrorCode_Error_Config    ErrorCode = 2 ///////////////////////////////////////////////////////////////////////////////////////////////////
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "Error_OK",
		1: "Error_Parameter",
		2: "Error_Config",
	}
	ErrorCode_value = map[string]int32{
		"Error_OK":        0,
		"Error_Parameter": 1,
		"Error_Config":    2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type EnumAttribute int32

const (
	EnumAttribute_Attr_CurHP     EnumAttribute = 0
	EnumAttribute_Attr_MaxHP     EnumAttribute = 1
	EnumAttribute_Attr_CurMP     EnumAttribute = 2
	EnumAttribute_Attr_MaxMP     EnumAttribute = 3
	EnumAttribute_Attr_MinPhyDam EnumAttribute = 4
	EnumAttribute_Attr_MaxPhyDam EnumAttribute = 5
	EnumAttribute_Attr_Armor     EnumAttribute = 6
	EnumAttribute_Attr_Dodge     EnumAttribute = 7
)

// Enum value maps for EnumAttribute.
var (
	EnumAttribute_name = map[int32]string{
		0: "Attr_CurHP",
		1: "Attr_MaxHP",
		2: "Attr_CurMP",
		3: "Attr_MaxMP",
		4: "Attr_MinPhyDam",
		5: "Attr_MaxPhyDam",
		6: "Attr_Armor",
		7: "Attr_Dodge",
	}
	EnumAttribute_value = map[string]int32{
		"Attr_CurHP":     0,
		"Attr_MaxHP":     1,
		"Attr_CurMP":     2,
		"Attr_MaxMP":     3,
		"Attr_MinPhyDam": 4,
		"Attr_MaxPhyDam": 5,
		"Attr_Armor":     6,
		"Attr_Dodge":     7,
	}
)

func (x EnumAttribute) Enum() *EnumAttribute {
	p := new(EnumAttribute)
	*p = x
	return p
}

func (x EnumAttribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumAttribute) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (EnumAttribute) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x EnumAttribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumAttribute.Descriptor instead.
func (EnumAttribute) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// /////////////////////////////////////////////////////////////////////////////////////////////////
// All other message pack to this message buffer
type CommonMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Opcode Opcode `protobuf:"varint,1,opt,name=Opcode,proto3,enum=meproto.Opcode" json:"Opcode,omitempty"`
	Buffer []byte `protobuf:"bytes,2,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
}

func (x *CommonMessage) Reset() {
	*x = CommonMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonMessage) ProtoMessage() {}

func (x *CommonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonMessage.ProtoReflect.Descriptor instead.
func (*CommonMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonMessage) GetOpcode() Opcode {
	if x != nil {
		return x.Opcode
	}
	return Opcode_ID_Null
}

func (x *CommonMessage) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type ErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        ErrorCode `protobuf:"varint,1,opt,name=Code,proto3,enum=meproto.ErrorCode" json:"Code,omitempty"`
	ErrorString string    `protobuf:"bytes,2,opt,name=ErrorString,proto3" json:"ErrorString,omitempty"`
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorMessage) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_Error_OK
}

func (x *ErrorMessage) GetErrorString() string {
	if x != nil {
		return x.ErrorString
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x4f, 0x70, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x4f, 0x70, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x0c, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x2a, 0x40, 0x0a, 0x06, 0x4f, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x44, 0x5f, 0x4e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x44,
	0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x49, 0x44, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x10, 0x02, 0x2a, 0x40, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x10, 0x02, 0x2a, 0x97, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x75, 0x6d,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x74, 0x74,
	0x72, 0x5f, 0x43, 0x75, 0x72, 0x48, 0x50, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x74, 0x74,
	0x72, 0x5f, 0x4d, 0x61, 0x78, 0x48, 0x50, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x74, 0x74,
	0x72, 0x5f, 0x43, 0x75, 0x72, 0x4d, 0x50, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x74, 0x74,
	0x72, 0x5f, 0x4d, 0x61, 0x78, 0x4d, 0x50, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x74, 0x74,
	0x72, 0x5f, 0x4d, 0x69, 0x6e, 0x50, 0x68, 0x79, 0x44, 0x61, 0x6d, 0x10, 0x04, 0x12, 0x12, 0x0a,
	0x0e, 0x41, 0x74, 0x74, 0x72, 0x5f, 0x4d, 0x61, 0x78, 0x50, 0x68, 0x79, 0x44, 0x61, 0x6d, 0x10,
	0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x5f, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x10,
	0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x5f, 0x44, 0x6f, 0x64, 0x67, 0x65, 0x10,
	0x07, 0x42, 0x0f, 0x5a, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x2f, 0x6d, 0x65, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []interface{}{
	(Opcode)(0),           // 0: meproto.Opcode
	(ErrorCode)(0),        // 1: meproto.ErrorCode
	(EnumAttribute)(0),    // 2: meproto.EnumAttribute
	(*CommonMessage)(nil), // 3: meproto.CommonMessage
	(*ErrorMessage)(nil),  // 4: meproto.ErrorMessage
}
var file_common_proto_depIdxs = []int32{
	0, // 0: meproto.CommonMessage.Opcode:type_name -> meproto.Opcode
	1, // 1: meproto.ErrorMessage.Code:type_name -> meproto.ErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
